project:
  type: website
  render:
    - index.qmd
    - report.qmd
    - literature.qmd
    - about.qmd

website:
  title: "Credit Risk Assessment using LightGBM"
  navbar:
    tools:
      - icon: github
        href: https://github.com/supriyasathe/IDC6940_LightGBM-agentic-ai-credit-risk
    left:
      - href: index.qmd
        text: Home
      - href: literature.qmd
        text: Literature
      - href: report.qmd
        text: Report
      - about.qmd

format:
  html:
    theme:
      light: lightly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true       # <--- Enable code folding globally for all code blocks

csl: apa-numeric-superscript-brackets.csl
# csl: american-sociological-association.csl
#csl: asa.csl